# Copyright (c) 2009-2010 Satoshi Nakamoto
# Distributed under the MIT/X11 software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

DEPSDIR:=/usr/i586-mingw32msvc

USE_UPNP:=0
USE_LEVELDB:=1

INCLUDEPATHS= \
 -I"$(CURDIR)" \
 -I"$(CURDIR)"/obj \
 -I"$(DEPSDIR)/boost_1_50_0" \
 -I"$(DEPSDIR)/db-4.8.30.NC/build_unix" \
 -I"$(DEPSDIR)/openssl-1.0.1c/include" \
 -I"$(DEPSDIR)"
